In [1]:
import numpy as np

## Looping Through Arrays

In [18]:
arrA = np.array([(11, 12, 13), (14, 15, 16)])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [19]:
for x in arrA:
    print(x * 2)
    # Each x is a full row: [11,12,13] then [14,15,16]

[22 24 26]
[28 30 32]


In [20]:
for x in arrA:
    for y in x:
        print(y * 2)
        # Each y is a single number: 11, 12, 13, 14, 15, 16

22
24
26
28
30
32


In [21]:
for x in arrA:
    for y in x:
        loop_result = x * 2 
        print(loop_result)
        # loop result uses x and not y so it prints the whole row doubled every iteration

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [23]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)
# stacks vertically and adds more rows

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [24]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)
# stacks horizontally and adds more columns

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [25]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)
# np.stack() requires all input arrays to have the same shape

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [26]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)
# joined_array_1 has 4 rows and arrA has 2 rows, to stack side by side using axis=1

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [27]:
h = np.hstack((arrA, arrA))
print(h)
# hstack adds columns side by side, like spreading a table wider

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [28]:
v = np.vstack((arrA, arrA))
print(v)
# vstack adds rows on top of each other like stacking two tables

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [29]:
d = np.dstack((arrA, arrA))
print(d)
# dstack creates depth layers turning 2D arrays into 3D arrays

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


In [30]:
# Splitting Arrays
splitsky = np.split(joined_array_1, 2)
print(splitsky)
# Returns 2 arrays, each with 2 rows and 3 columns

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [33]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# using spliterino = np.split was raising an error, it doesnt divide evenly.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [34]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)
# checks each element is divisble by 2
# if true: keeps original value
# if false: replaces with the string odd

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [35]:
arrB = np.array([(7, 6), (13, 5), (7, 3)])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)
# np.sort sorts each row independently from left to right

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [36]:
print(arrB)
z = arrB < 7  # a boolean mask where its true where value < 7
arrC = arrB[z]    # a mask to return matching values as 1D array
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [38]:
# a filter to bring values greater than of equal to 7
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[ 7 13  7]
