# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

[16  1]


In [3]:
r_2 = np.random.randint(1, 21, size=(1, 2))
print(r_2)

[[10 18]]


In [4]:
r_3 = np.random.random(size=(2, 1))
print(r_3)

[[0.26540643]
 [0.5706346 ]]


In [5]:
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

[[88 41 82 44 81]
 [37 82 31 59 93]
 [85 59 84 94 49]
 [59 23 26 59 30]]


In [6]:
r_5 = np.random.random(size=(4, 5))
print(r_5)

[[0.19324847 0.086925   0.46731046 0.19689071 0.48962816]
 [0.89830388 0.1255812  0.31680926 0.65204194 0.59486963]
 [0.31805449 0.70344023 0.66033086 0.36848108 0.75725142]
 [0.11987564 0.41766906 0.45896169 0.80330963 0.17118556]]


## Generating Random Choices from an Array

In [9]:
students = np.array([
    'Alice', 'Bob','Carlos','Diana','Eve','Frank','Grace', 'Hector', 'Isabel', 'James', 'Karen', 'Luis'
])
print(students)

['Alice' 'Bob' 'Carlos' 'Diana' 'Eve' 'Frank' 'Grace' 'Hector' 'Isabel'
 'James' 'Karen' 'Luis']


In [10]:
call_on = np.random.choice(students)
print(call_on)

Diana


In [11]:
breakout_groups = np.random.choice(students, size=(3, 4), replace=False)
print(breakout_groups)
# Using replace false with 12 students filing a 3 by 4 grid means each student appears once
# no one is left out and no one is repeated. Its an effective way to randomly assign breakout groups
# as long as the class size matches the total number of slots in the grid

[['Luis' 'Hector' 'Eve' 'Diana']
 ['Isabel' 'Carlos' 'Bob' 'Alice']
 ['Frank' 'James' 'Karen' 'Grace']]


In [12]:
# using probability values (p) for each of the students, sum to 1.0
# anything with a 0 will never be called on
p_values = [0.30, 0.20, 0.15, 0.10, 0.08, 0.07, 0.04, 0.03, 0.02, 0.01, 0.00, 0.00]
call_on_weighted = np.random.choice(students, size=5, p=p_values)
print(call_on_weighted)

['Bob' 'Alice' 'Carlos' 'Alice' 'Bob']


## Generating a Normal Distribution

In [14]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[ 4.42570644 21.88014767 19.84687584  3.00979703 13.47710196]
 [13.38485264  9.47333476 11.71983298 10.56957331 10.34042073]
 [17.85330262 13.69308679  6.25037076 10.30058448 14.66433489]
 [ 6.11310589 13.67285825 13.48662543 14.99861372 10.19246428]]
