# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [3]:
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.random(size=(2, 1))
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.random(size=(4, 5))
print('r_1:', r_1)
print('r_2:\n', r_2)
print('r_3:\n', r_3)
print('r_4:\n', r_4)
print('r_5:\n', r_5)

r_1: [18  1]
r_2:
 [[6 1]]
r_3:
 [[0.49396815]
 [0.14291925]]
r_4:
 [[ 52 100  39  97  35]
 [ 70  25  56  27  40]
 [ 98  91  93  88  45]
 [ 39  77  47  77  70]]
r_5:
 [[0.28824072 0.36842778 0.58685077 0.98743222 0.22646957]
 [0.99305025 0.88255821 0.58491985 0.84517535 0.93139296]
 [0.95767492 0.70516418 0.21839091 0.97856647 0.41630696]
 [0.64251814 0.64253792 0.68187265 0.33157506 0.89484687]]


## Permutations

In [4]:
print(r_4)

[[ 52 100  39  97  35]
 [ 70  25  56  27  40]
 [ 98  91  93  88  45]
 [ 39  77  47  77  70]]


In [5]:
np.random.shuffle(r_4)
print(r_4)

[[ 39  77  47  77  70]
 [ 98  91  93  88  45]
 [ 70  25  56  27  40]
 [ 52 100  39  97  35]]


The elements were shuffled with np.random.shuffle() on a 2-D array. The rows themselves are rearranged. With the rows changing, the values within those rows stay together in the same order. Individual elements are not scattered across rows, the rows are swapped as units because shuffle operates along axis=0 by default.

In [7]:
new_shuffle = np.random.permutation(r_4)
print('new_shuffle:\n', new_shuffle)
print('\nr_4 (original, unchanged):\n', r_4)

new_shuffle:
 [[ 98  91  93  88  45]
 [ 70  25  56  27  40]
 [ 52 100  39  97  35]
 [ 39  77  47  77  70]]

r_4 (original, unchanged):
 [[ 39  77  47  77  70]
 [ 98  91  93  88  45]
 [ 70  25  56  27  40]
 [ 52 100  39  97  35]]


"When to use shuffle and permutation": 
Shuffle: You'll use this when you want to rearrange the original array in place and don't need the original order anymore.
Permutation: You'll use this when you want a new shuffled copy while leaving the original untouched. A safer route when you still need the original for comparison or for calculations.

## Mathematical Operations

In [8]:
print('r_1:', r_1, ' shape:', r_1.shape)
print('r_2:\n', r_2, '  shape:', r_2.shape)
result_12 = np.add(r_1, r_2)
print('r_1 + r_2:\n', result_12, '  shape:', result_12.shape)

r_1: [18  1]  shape: (2,)
r_2:
 [[6 1]]   shape: (1, 2)
r_1 + r_2:
 [[24  2]]   shape: (1, 2)


In [9]:
print('r_1:', r_1, '  shape:', r_1.shape)
print('r_3:\n', r_3, '  shape:', r_3.shape)
result_13 = np.add(r_1, r_3)
print('r_1 + r_3:\n', result_13, '  shape:', result_13.shape)

r_1: [18  1]   shape: (2,)
r_3:
 [[0.49396815]
 [0.14291925]]   shape: (2, 1)
r_1 + r_3:
 [[18.49396815  1.49396815]
 [18.14291925  1.14291925]]   shape: (2, 2)


In [10]:
print('r_2:\n', r_2, '  shape:', r_2.shape)
print('r_4:\n', r_4, '  shape:', r_4.shape)
try:
    result_24 = np.add(r_2, r_4)
    print('r_2 + r_4:\n', result_24, '  shape:', result_24.shape)
except ValueError as e:
    print('Error:', e)

r_2:
 [[6 1]]   shape: (1, 2)
r_4:
 [[ 39  77  47  77  70]
 [ 98  91  93  88  45]
 [ 70  25  56  27  40]
 [ 52 100  39  97  35]]   shape: (4, 5)
Error: operands could not be broadcast together with shapes (1,2) (4,5) 


In [11]:
# r_1 shape vs r_4 shape
try:
    print(np.add(r_1, r_4))
except ValueError as e:
    print('r_1 + r_4 Error:', e)

# r_2 shape vs r_4 shape
try:
    print(np.add(r_2, r_4))
except ValueError as e:
    print('r_2 + r_4 Error:', e)

# r_3 shape vs r_4 shape
try:
    print(np.add(r_3, r_4))
except ValueError as e:
    print('r_3 + r_4 Error:', e)

r_1 + r_4 Error: operands could not be broadcast together with shapes (2,) (4,5) 
r_2 + r_4 Error: operands could not be broadcast together with shapes (1,2) (4,5) 
r_3 + r_4 Error: operands could not be broadcast together with shapes (2,1) (4,5) 


In [16]:
# what happens with np.array([1]) to r_4 (broadcasts to (1,1) and then (4,5)
print(np.add(np.array([1]), r_4))

[[ 40  78  48  78  71]
 [ 99  92  94  89  46]
 [ 71  26  57  28  41]
 [ 53 101  40  98  36]]


In [17]:
# what happens with np.array([[1]]), r_4 (broadcasts to match (4,5) perfectly)
print(np.add(np.array([[1]]), r_4))

[[ 40  78  48  78  71]
 [ 99  92  94  89  46]
 [ 71  26  57  28  41]
 [ 53 101  40  98  36]]


In [18]:
# what happens with np.array([1,1,1,1,1]) to r_4 (treated as (1,5) then broadcasts to (4,5))
print(np.add(np.array([1, 1, 1, 1, 1]), r_4))

[[ 40  78  48  78  71]
 [ 99  92  94  89  46]
 [ 71  26  57  28  41]
 [ 53 101  40  98  36]]


In [19]:
try:
    print(np.add(np.array([[1], [1]]), r_4))
except ValueError as e:
    # The error could not be broadcasted together with shapes (2,1) and (4,5)
    # Where the first dimension is 2 but r_4's dimension is 4.
    # But since niether is 1, that makes the broadcast fail
    print('Error:', e)

Error: operands could not be broadcast together with shapes (2,1) (4,5) 


### How does broadcasting work?
NumPy compares the shapes from the compatible inward dimension. If two dimensions are compatible then they are equal or if one of them is 1. The result takes the larger size in each of the dimensions for example shape (5,) is treated as (1,5) due to np.array([1,1,1,1,1]). It'll then broadcast across all 4 rows of "r_4" (4,5) by adding 1 to every element. If any of the dimensions is incompatible or not equal to 1 then it'll raise a ValueError.

## Rounding

In [20]:
print(r_3)

[[0.49396815]
 [0.14291925]]


In [21]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [22]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [23]:
print(np.floor(r_3))

[[0.]
 [0.]]


In [24]:
print(np.ceil(r_3))

[[1.]
 [1.]]


In [25]:
print(np.round(r_3, 2))

[[0.49]
 [0.14]]


## Cumulative Operations

In [26]:
print(r_4)

[[ 39  77  47  77  70]
 [ 98  91  93  88  45]
 [ 70  25  56  27  40]
 [ 52 100  39  97  35]]


In [27]:
print(np.sum(r_4))

1266


In [28]:
print(np.sum(r_4, axis=0))

[259 293 235 289 190]


In [29]:
print(np.sum(r_4, axis=1))

[310 415 218 323]


In [30]:
print(np.cumsum(r_4))

[  39  116  163  240  310  408  499  592  680  725  795  820  876  903
  943  995 1095 1134 1231 1266]


In [31]:
print(np.cumsum(r_4, axis=0))

[[ 39  77  47  77  70]
 [137 168 140 165 115]
 [207 193 196 192 155]
 [259 293 235 289 190]]


## Grocery Problem

In [32]:
# Bag1: 2 Vegetables, 3 fruits, 4 snacks, 0 beverages
# Bag2: 4 vegetables, 0 fruits, 1 snack, 2 beverages
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])
print('bag1:', bag1)
print('bag2:', bag2)

bag1: [2 3 4 0]
bag2: [4 0 1 2]


In [34]:
bag1_total = np.sum(bag1)
bag2_total = np.sum(bag2)
print(f"The first bag contains {bag1_total} items, and the second bag contains {bag2_total} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [37]:
category_totals = bag1 + bag2
print(f'''
There are {category_totals[0]} vegetables, {category_totals[1]} fruits, {category_totals[2]} boxes of snacks, and {category_totals[3]} beverages in the two grocery bags.
''')


There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.



## Teamwork

In [38]:
# Ali knocked on: Monday 5, Tuesday 4, Wedsnesday 6, Thursday 4, Friday 2
ali = np.array([5, 4, 6, 4, 2])
print('Ali:', ali)

Ali: [5 4 6 4 2]


In [39]:
# Ben missed Monday so Monday 0, then Tuesday 5, Weds 5, Thursday 3, Friday 4
ben = np.array([0, 5, 5, 3, 4])
print('Ben:', ben)

Ben: [0 5 5 3 4]


In [40]:
# Carla knocked on: Monday 3, Tuesday 6, missed Weds 0, Thursday 3, Friday 4
carla = np.array([3, 6, 0, 3, 4])
print('Carla:', carla)

Carla: [3 6 0 3 4]


In [41]:
# Each row is one person, each column is one day (mon-fri)
all_knocks = np.array([ali, ben, carla])
print('all_knocks:')
print(all_knocks)

all_knocks:
[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [42]:
# Sum along axis=1
per_person = np.sum(all_knocks, axis=1)
print(f'''
Ali knocked on {per_person[0]} doors this week.
Ben knocked on {per_person[1]} doors this week.
Carla knocked on {per_person[2]} door this week.
''')

total_collective = np.sum(all_knocks)
print(f"The group collectively knocked on {total_collective} doors.")


Ali knocked on 21 doors this week.
Ben knocked on 17 doors this week.
Carla knocked on 16 door this week.

The group collectively knocked on 54 doors.


In [43]:
# 1. Sum across all people per day with axis=0
daily_totals = np.sum(all_knocks, axis=0)

# 2. Cumulative (rolling) total of door-knocks day by day
rolling_daily = np.cumsum(daily_totals)

# 3. Every 2 door-knocks = 1 estimated vote, so multiply rolling by 0.5
estimated_votes = rolling_daily * 0.5

print("Rolling total of estimated votes turned out, Mon through Fri:")
print(estimated_votes)

Rolling total of estimated votes turned out, Mon through Fri:
[ 4.  11.5 17.  22.  27. ]
