In [1]:
# Arrays

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(matrix)
print(matrix[1][2])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
6


In [5]:
cube = [        # level 1 - the whole cube
    [           # level 2 - first "layer"
        [1, 2], # level 3 - rows
        [3, 4]
    ],
    [           # level 2 - second "layer"
        [5, 6],
        [7, 8]
    ]
]

print(cube)
print(cube[1][0][1])  # → 6

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
6


In [7]:
# Arrays and Attributes

# 1D ARRAY

import numpy as np

arr_1d = np.array([10, 20, 30, 40, 50])

print("=== 1D Array ===")
print(arr_1d)

# Accessing elements in 1D array with index
print(arr_1d[0])
print(arr_1d[2])
print(arr_1d[-1])

=== 1D Array ===
[10 20 30 40 50]
10
30
50


In [8]:
# 2D Array

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("=== 2D Array ===")
print(arr_2d)

# Accessing elements in 2D array

print("Element at row 0, col 0:", arr_2d[0][0])
print("Element at row 1, col 2:", arr_2d[1][2])
print("Element at row 2, col 1:", arr_2d[2][1])

print("\n")

=== 2D Array ===
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, col 0: 1
Element at row 1, col 2: 6
Element at row 2, col 1: 8




In [10]:
# 3D Array

arr_3d = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print("=== 3D Array ===")
print(arr_3d)

# Accessing elements in 3D array

print("Element at layer 0, row 1, col 1:", arr_3d[0][1][1])
print("Element at layer 1, row 0, col 0:", arr_3d[1][0][0])

print("\n=== End of Program ===")

=== 3D Array ===
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Element at layer 0, row 1, col 1: 4
Element at layer 1, row 0, col 0: 5

=== End of Program ===
