In [1]:
import numpy as np

In [9]:
# 1D Array

arr1 = np.array([1, 2, 3])

print(arr1)
print(f"Shape: {arr1.shape}")
print(f"Dimensions: {arr1.ndim}")

[1 2 3]
Shape: (3,)
Dimensions: 1


In [8]:
# 2D array
arr2 = np.array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]
])

print(arr2)
print(f"Shape: {arr2.shape}")
print(f"Dimensions: {arr2.ndim}")

[[1 2 3]
 [1 2 3]
 [1 2 3]]
Shape: (3, 3)
Dimensions: 2


In [7]:
# 3D Array

arr3 = np.array([
    [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]],
    [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]],
    [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]
])

print(arr3)
print(f"Shape: {arr3.shape}")
print(f" Dimensions: {arr3.ndim}")

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]
Shape: (3, 4, 3)
 Dimensions: 3


In [11]:
# Arrays
print("=== NumPy Array Creations Functions ===\n")

# 1 array()
a = np.array([1, 2, 3, 4, 5])
print("np.array([1,2,3,4,5])")
print(a, "\n")

=== NumPy Array Creations Functions ===

np.array([1,2,3,4,5])
[1 2 3 4 5] 



In [12]:
# 2 zeros() - array of zeros
b = np.zeros((2, 3))
print("np.zeros((2,3))")
print(b, "\n")

np.zeros((2,3))
[[0. 0. 0.]
 [0. 0. 0.]] 



In [13]:
# 3  ones() - array of ones
c = np.ones((2, 2))
print("np.ones((2,2))")
print(c, "\n")

np.ones((2,2))
[[1. 1.]
 [1. 1.]] 



In [14]:
# 4 full() - array filled with a constant value
d = np.full((3, 2), 7)
print("np.full((3,2), 7)")
print(d, "\n")

np.full((3,2), 7)
[[7 7]
 [7 7]
 [7 7]] 



In [15]:
# Arrays
a = np.array([10, 20, 30, 40])
print(a * 2)
print(a.mean())
print(a.dtype)

[20 40 60 80]
25.0
int64


In [19]:
# Create 2D NumPu array
a = np.array([[10, 20, 30],
             [40, 50, 60]])
print("Array:")
print(a)

# Shape
print("\nShape of array:", a.shape)

# .ndim
print("Number of dimensions (ndim):", a.ndim)

# .dtype - Data Type
print("Data type (dtype):", a.dtype)

# .size
print("total number of elements:", a.size)

Array:
[[10 20 30]
 [40 50 60]]

Shape of array: (2, 3)
Number of dimensions (ndim): 2
Data type (dtype): int64
total number of elements: 6
