In [1]:
import numpy as np

In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.concatenate([arr1, arr2])
print(arr3)

[1 2 3 4 5 6]


In [5]:
# join 2D arrays

arrA = np.array([
    [1, 2],
    [3, 4]
])

arrB = np.array([
    [5, 6],
    [7, 8]
])

# join it
result2 = np.concatenate((arrA, arrB), axis=1)
print(result2)

[[1 2 5 6]
 [3 4 7 8]]
