In [1]:
import numpy as np

In [2]:
# 1. 

arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])

print(arrA)

[[11 12 13]
 [14 15 16]]


In [3]:
# 2.
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [8]:
# 3.
for x in arrA:
    for y in x:
        loop_result = y * 2
        #4
        print(loop_result)

22
24
26
28
30
32
