In [1]:
import numpy as np

In [6]:
# a) Standard Python List
fruits = ['apple', 'banana', 'cherry', 'date']

# 1D NumPy from the list
arr_1 = np.array(fruits)
print(arr_1)

# Check data type
print(arr_1.dtype)

# 2D array
arr_2 = np.array([(10, 11, 12), (13, 14, 15)])
print(arr_2)

# Transpose
print(arr_2.T)

# Does .T change itself?
print(arr_2)

# Another 2D array
arr_3 = np.array([(1, 3, 5), (2, 4, 6)])
print(arr_3)

# 1D array using slicing from arr_3
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)

# 3D array of all 1's
arr_5 = np.ones((2, 2, 2))
print(arr_5)

['apple' 'banana' 'cherry' 'date']
<U6
[[10 11 12]
 [13 14 15]]
[[10 13]
 [11 14]
 [12 15]]
[[10 11 12]
 [13 14 15]]
[[1 3 5]
 [2 4 6]]
[5 4]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
